// TEMPORARILY DISABLED: Firebase Cloud Messaging
/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxL9hMjiOB4aXNm6wUuT1zIU-BjLdT4U',
    appId: '1:723653831340:web:5d5371e134dbfa40c90d09',
    messagingSenderId: '723653831340',
    projectId: 'hiddify-me',
    authDomain: 'hiddify-me.firebaseapp.com',
    storageBucket: 'hiddify-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBagOLJ8SBXE4pBjsjgRRStpXQzLdXYOBI',
    appId: '1:723653831340:android:7691cb31873acf7ac90d09',
    messagingSenderId: '723653831340',
    projectId: 'hiddify-me',
    storageBucket: 'hiddify-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2pgVwPpHtNTVfjW_dVR-L0Gx5JrSkDMg',
    appId: '1:723653831340:ios:c83bc119cdc545bdc90d09',
    messagingSenderId: '723653831340',
    projectId: 'hiddify-me',
    storageBucket: 'hiddify-me.firebasestorage.app',
    iosBundleId: 'com.hiddify.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2pgVwPpHtNTVfjW_dVR-L0Gx5JrSkDMg',
    appId: '1:723653831340:ios:bdfbbfdac8a141d7c90d09',
    messagingSenderId: '723653831340',
    projectId: 'hiddify-me',
    storageBucket: 'hiddify-me.firebasestorage.app',
    iosBundleId: 'app.hiddify.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqxL9hMjiOB4aXNm6wUuT1zIU-BjLdT4U',
    appId: '1:723653831340:web:2ebdfc174ee341f3c90d09',
    messagingSenderId: '723653831340',
    projectId: 'hiddify-me',
    authDomain: 'hiddify-me.firebaseapp.com',
    storageBucket: 'hiddify-me.firebasestorage.app',
  );

}
*/
